### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by hutek** [Scrimp-Ink/.github#1]
test issue
![lebron](https://github.com/user-attachments/assets/d0ebe226-4dcd-4deb-8e96-68802cc0124b)

**Comment by hutek** [comment]
oooaaaaaaaaghhhhhh

**Comment by e34rrsff** [comment]
Cat caught mouse. What do

**Comment by e34rrsff** [comment]
Bruh these devs suck

**Comment by hutek** [comment]
we dont suck 💢
